# Nom de l'application
spring.application.name=Rv_Compta

# Desactive le serveur web par defaut
spring.main.web-application-type=none

# 2. Axe Stockage : Où stocke-t-on les données ? (json ou bdd)
rvcompta.storage.type=json

# Imports (.env pour les profils locaux/externes)
spring.config.import=optional:file:src/main/resources/.env/, classpath:app-info.properties

# Logique de base : on d\u00E9finit la racine par defaut (le projet)
app.base.path=${user.dir}
app.data.folder=data
# On assemble le tout ici une seule fois
app.data.path=${app.base.path}/${app.data.folder}/

# ===================================================================
# SEED CONFIGURATION (COMMON STRUCTURE AND VALUE)
# ===================================================================
app.persistence.seed-path=classpath:data/
#app.persistence.seed-path=${app.base.path}/${app.persistence.seed.folder-name}

# ===================================================================
# PERSISTENCE CONFIGURATION (COMMON STRUCTURE)
# ===================================================================
app.persistence.folder-name=./data

# Assemblage dynamique du chemin complet (Windows/Linux friendly)
app.persistence.storage-path=${app.base.path}/${app.persistence.folder-name}/

# --- PERSISTENCE : FILEs pcg ---
app.persistence.file-name.pcg=pcg.json

# --- PERSISTENCE : FILEs REFERENTIAL ---
app.persistence.file-name.status=OperationStatuts.json
app.persistence.file-name.paymentMethod=PaymentMethod.json

# --- PERSISTENCE : FILEs pcp ---
app.persistence.file-name.tiers=Tiers.json
app.persistence.file-name.details=details.json

# --- PERSISTENCE : FILEs COMPTA ---
app.persistence.file-name.diary=compta.json





