# ===================================================================
# CONFIGURATION PAR DÉFAUT DU MODULE MÉTIER : COMPTA
# ===================================================================
# Ce module est une brique métier autonome. Si l'utilisateur choisit d'installer
# ce module, ces propriétés servent de socle technique de base.
# D'autres modules optionnels (Stock, Personnel/RH) auront leurs propres fichiers.

# Type de stockage par défaut utilisé par le moteur comptable
rvcompta.storage.type=json

# Configuration structurelle des dossiers de persistance
app.persistence.folder-name=./data
app.persistence.seed-path=classpath:data/

# Définition des noms de fichiers standardisés (Dot-Notation unifiée)
app.persistence.file-name.pcg=pcg.json
app.persistence.file-name.status=OperationStatuts.json
app.persistence.file-name.paymentMethod=PaymentMethod.json
app.persistence.file-name.journal=journal.json
app.persistence.file-name.operation=operation.json