# Nom de l'application
spring.application.name=Rv_Compta

# Imports
spring.config.import=optional:file:src/main/resources/.env/, classpath:app-info.properties

# Logique de base : on definit la racine par defaut (le projet)
app.base.path=${user.dir}
# On definit le dossier cible
app.data.folder=data

# On assemble le tout ici une seule fois
app.data.path=${app.base.path}/${app.data.folder}/