# --- CONFIGURATION ENVIRONNEMENTALE (DEV / WINDOWS) ---
# La version vient de Maven via app-info.properties

# Logique de chemin heritee de application.properties
# Aucun changement requis pour app.base.path sur Windows

# Niveau de log detaille pour le developpement
logging.level.com.jtissdev_API=DEBUG