# ===================================================================
# CONFIGURATION GLOBALE - CONSOLE VIEW (CLI)
# ===================================================================
spring.application.name=rv-compta-cli

# Spécifique à la Console : On désactive totalement le serveur web embarqué
spring.main.web-application-type=none
spring.main.banner-mode=off

# IMPORTATION DYNAMIQUE DES CONFIGURATIONS DES MODULES INSTALLÉS
spring.config.import=optional:classpath:.env/, classpath:app-info.properties, optional:classpath:compta-default.properties

# Logique de calcul dynamique des chemins de base de l'application exécutée
app.base.path=${user.dir}
app.persistence.storage-path=${app.base.path}/${app.persistence.folder-name}/