# ===================================================================
# PROFIL : DEVELOPMENT (LOCAL WINDOWS) - API SERVER
# ===================================================================
server.port=8080

# Surcharge locale du chemin de stockage pour le développement sur machine physique
app.persistence.storage-path=C:/Users/jtiss/Documents/Developpement/Data/dev/

# Logs détaillés pour le suivi du trafic web en cours de développement
logging.level.org.springframework.web=INFO
logging.level.com.jtissdev=DEBUG