# ===================================================================
# PROFIL : PRODUCTION (RASPBERRY PI) - API SERVER
# ===================================================================
server.port=80

# Chemin absolu immuable sur le serveur de production Linux
app.persistence.storage-path=/var/rvcompta/prod/data/

# Optimisation des logs pour éviter la saturation disque en production
logging.level.org.springframework=WARN
logging.level.com.jtissdev=INFO