# ===================================================================
# PROFIL : TEST (JUNIT INTEGRATION) - API SERVER
# ===================================================================
server.port=0

# Utilisation du dossier temporaire natif de l'OS pour garantir l'étanchéité totale des tests
app.persistence.storage-path=${java.io.tmpdir}/rvcompta-test/data/

logging.level.org.springframework=WARN
logging.level.com.jtissdev=WARN