# ===================================================================
# PROFIL : STAGING (DEMO / SHOW) - API SERVER
# ===================================================================
server.port=8081

# Dossier d'isolation des données pour l'environnement de démonstration (Staging)
app.persistence.storage-path=/var/rvcompta/staging/data/

logging.level.org.springframework.web=INFO
logging.level.com.jtissdev=INFO