# ===================================================================
# PROFIL : DEVELOPMENT (LOCAL WINDOWS) - CONSOLE VIEW
# ===================================================================
app.persistence.storage-path=C:/Users/jtiss/Documents/Developpement/Data/dev/

logging.level.org.springframework=WARN
logging.level.com.jtissdev=INFO