# ===================================================================
# ENVIRONNEMENT : PRODUCTION (RASPBERRY PI) - CONSOLE VIEW
# ===================================================================
logging.level.org.springframework=ERROR
logging.level.com.jtissdev=INFO

app.persistence.storage-path=/home/jtiss/rvcompta-view/prod/data/
