# ===================================================================
# CONFIGURATION - ENVIRONNEMENT : DEVELOPMENT (LOCAL WINDOWS)
# ===================================================================
# --- PERSISTENCE : DOSSIERS ---
# Le dossier "vivant" pour le developpement
app.persistence.storage-path=./data/dev
# Le chemin de base integre au code source
app.persistence.seed-path=classpath:data/

# --- PERSISTENCE : FICHIERS COMPTA ---
app.persistence.file-name.journal=comptaDev.json