# ===================================================================
# CONFIGURATION - ENVIRONNEMENT : TESTING Suite
# ===================================================================
# --- PERSISTENCE : DOSSIERS ---
# Le dossier "vivant" pour les tests, toujours detruit et recree par Maven
app.persistence.storage-path=./target/test-storage

app.base.path=${java.io.tmpdir}/rv_compta_test
# --- TEST DATA SET ---
app.test.data-set.path = classpath:data/

app.test.data-set.pcg = pcg.json
app.test.data-set.paymentMethod = paymentMethod-test.json
app.test.data-set.status = Status-test.json
app.test.data-set.details = details-test.json
app.test.data-set.tiers = tiers-test.json
app.test.data-set.diary = journal-test.json

# --- PERSISTENCE : FICHIERS COMPTA ---
app.persistence.file-name.journal=comptaTest.json

# Aliases pour aligner le fichier de configuration avec les @Value du PcgRepository
app.persistence.seed-path=${app.test.data-set.path}
app.persistence.file-name.pcg=${app.test.data-set.pcg}