# --- MODE : API ---

# Reactive le serveur web (Tomcat embarqued) pour exposer les endpoints REST
spring.main.web-application-type=servlet
server.port=8080

# Logs specifiques au web
logging.level.org.springframework.web=INFO