# ===================================================================
# CONFIGURATION - ENVIRONNEMENT : PRODUCTION (RASPBERRY PI)
# ===================================================================
## commande de lancement api : java -jar -Dspring.profiles.active=prod,api Rv_Compta.jar
## commande de lancement console : java -jar -Dspring.profiles.active=prod,console Rv_Compta.jar

## PRODUCTION : ## PRODUCTION : default file-name (compta.json) pour la persistance

# --- PERSISTENCE : DOSSIERS ---
# Le dossier "vivant" en production sur la Raspberry Pi
app.persistence.storage-path=./data/prod
