# --- MODE : CONSOLE ---

# On fait taire Spring au demarrage pour ne pas pousser le menu vers le haut
spring.main.banner-mode=off
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# Mais on garde tes logs de metier en INFO pour voir tes actions
logging.level.com.jtissdev=INFO

# On active l'UI uniquement pour ce profil
app.ui.mode=true