# ===================================================================
# CONFIGURATION GLOBALE - API SERVER
# ===================================================================
spring.application.name=rv-compta-api

# Spécifique à l'API : On active explicitement le serveur web embarqué (Tomcat)
spring.main.web-application-type=servlet

# IMPORTATION DYNAMIQUE DES CONFIGURATIONS DES MODULES INSTALLÉS
# 1. 'optional:classpath:.env/' -> Charge l'environnement actif (dev, prod, etc.) depuis le dossier .env du JAR
# 2. 'classpath:app-info.properties' -> Charge les métadonnées générées par Maven (version, etc.)
# 3. 'optional:classpath:compta-default.properties' -> Importe les réglages si le module Compta est installé
# 4. À l'avenir, les autres modules métiers optionnels s'ajouteront ici sans casser l'application :
#    'optional:classpath:stock-default.properties', 'optional:classpath:rh-default.properties'
spring.config.import=optional:classpath:.env/, classpath:app-info.properties, optional:classpath:compta-default.properties

# Logique de calcul dynamique des chemins de base de l'application exécutée
app.base.path=${user.dir}
app.persistence.storage-path=${app.base.path}/${app.persistence.folder-name}/